/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class Messenger

fun main(args: Array<String>) {
    runApplication<Messenger>(*args)
}
