spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: messenger
    password: change-me
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:/db/migrations

  rabbitmq:
    username: messenger
    password: change-me
    host: localhost
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    defaultStatementTimeout: 1

messenger:
  mail:
    from: admin@example.org